apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: {{.Values.image.repository }}:{{.Values.image.tag }}   #gcr.io/klusternetes-dev/nodejs-sample:latest
        imagePullPolicy: Always
        name: nodejs-sample
      imagePullSecrets:
      - name: {{ .Values.secretName }}                            