
name: Deploy to knts on PR
on:
  pull_request:
    types: [opened, synchronize]
env:
  CI: false
jobs:
  build_and_preview:
    runs-on: 
    # - self-hosted
    - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: k8s-master@update
        with:
          version: v1.21.2-k3s1
          size: SMALL
          name: mycluster
          token: ${{ secrets.KNTS_TOKEN }}
      - run: |
          kubectl get nodes
